In [30]:
import numpy as np

## simple propagation rule

$ f(H^{i},A) = \sigma(AH^{i}W^{i}) $

for the first level
$ f(X,A) = AX  $

In [31]:
#  adjency matrix of a non-direct graph
A = np.matrix([
[0, 1, 0, 1],
[0, 0, 1, 1], 
[0, 0, 0, 1],
[0, 0, 0, 0]],
dtype=float)

A

matrix([[0., 1., 0., 1.],
        [0., 0., 1., 1.],
        [0., 0., 0., 1.],
        [0., 0., 0., 0.]])

In [32]:
# X features matrix two features for each node
X = np.matrix([
    [i, -i]
    for i in range(A.shape[0])
    ], dtype=float)

X

matrix([[ 0.,  0.],
        [ 1., -1.],
        [ 2., -2.],
        [ 3., -3.]])

In [33]:
A * X

matrix([[ 4., -4.],
        [ 5., -5.],
        [ 3., -3.],
        [ 0.,  0.]])

In [34]:
#take into account the node itselves

I = np.matrix(np.eye(A.shape[0]))

A_hat = A + I

A_hat * X

matrix([[ 4., -4.],
        [ 6., -6.],
        [ 5., -5.],
        [ 3., -3.]])

## Normalizing the Feature Representations

$ f(X, A) = D^{-1}AX $

In [39]:
D_hat = np.array(np.sum(A_hat, axis=0))[0]
D_hat = np.matrix(np.diag(D_hat))
D_hat

matrix([[1., 0., 0., 0.],
        [0., 2., 0., 0.],
        [0., 0., 2., 0.],
        [0., 0., 0., 4.]])

In [41]:
D_hat**-1 * A_hat * X

matrix([[ 4.  , -4.  ],
        [ 3.  , -3.  ],
        [ 2.5 , -2.5 ],
        [ 0.75, -0.75]])

In [45]:
W =  np.matrix([[1, -1],[-1, 1]])

D_hat**-1 * A_hat * X * W

matrix([[8. ],
        [6. ],
        [5. ],
        [1.5]])

In [48]:
#adding activation function
def relu(x):
    return (np.maximum(0, X))

relu(D_hat**-1 * A_hat * X * W)

matrix([[0., 0.],
        [1., 0.],
        [2., 0.],
        [3., 0.]])